### PR TITLE
fs-integration: Switch default host version to CentOS 9

### PR DESCRIPTION
**Pull request by anoopcs9**
depends on #54

### CODE REVIEW

**Comment by anoopcs9** [comment]
We're still waiting on _ansible-collection-ansible-utils_ to be [branched and built](https://bugzilla.redhat.com/show_bug.cgi?id=2033027) on EPEL 9.

**Comment by anoopcs9** [comment]
> We're still waiting on _ansible-collection-ansible-utils_ to be [branched and built](https://bugzilla.redhat.com/show_bug.cgi?id=2033027) on EPEL 9.

We have now switched to an alternate approach of installing necessary ansible collections via `ansible-galaxy` command line tool.

**Comment by anoopcs9** [comment]
Finally after ~4 months.. Ready for review 😊

**Review by phlogistonjohn — APPROVED** [review]
Looks OK to me.

**Pull request merged**
