### PR TITLE
jobs/scripts: Fix installation of `netaddr` python module

### PR DESCRIPTION
**Pull request by anoopcs9**
Ansible is built with Python 3.11 and thus required modules are searched from _/usr/lib/python3.11/site-packages_. Therefore force a version specific install of `netaddr` python module.

### CODE REVIEW

**Comment by xhernandez** [comment]
I think this PR should fix the issue (thanks !), but I'm wondering if there isn't a better way to manage this in general. What if at some point ansible decides to use python 3.12 ? all this will break. Isn't there any other better way to install python dependencies from ansible that is more future-proof ? I've done a quick search but I haven't found anything relevant.

**Comment by anoopcs9** [comment]
> I think this PR should fix the issue (thanks !), but I'm wondering if there isn't a better way to manage this in general. What if at some point ansible decides to use python 3.12 ? all this will break. Isn't there any other better way to install python dependencies from ansible that is more future-proof ? I've done a quick search but I haven't found anything relevant.

Before coming up with the change I remember trying to install python library dependencies with the help of **[ansible.builtin.pip](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html)** module. Let me double check to see if it can solve the issue in a more generic way.

**Comment by anoopcs9** [comment]
> > I think this PR should fix the issue (thanks !), but I'm wondering if there isn't a better way to manage this in general. What if at some point ansible decides to use python 3.12 ? all this will break. Isn't there any other better way to install python dependencies from ansible that is more future-proof ? I've done a quick search but I haven't found anything relevant.
> 
> Before coming up with the change I remember trying to install python library dependencies with the help of **[ansible.builtin.pip](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html)** module. Let me double check to see if it can solve the issue in a more generic way.

Unfortunately nothing works and I am starting to think that it is by design we have different python versions on el8. See the versions [table](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_introduction-to-python_configuring-basic-system-settings#con_python-versions_assembly_introduction-to-python) from RH docs. Unless we change the default python version, `python3` always indicates `python3.6`. Whereas latest ansible packages that we install are built with latest python version available on el8 i.e, `python3.11`. Therefore as mentioned in the docs:

> Always specify the version of Python when installing it, invoking it, or otherwise interacting with it.

Thus we may have to cope with such infrequent python version updates. For better clarity see Chapter [36](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_introduction-to-python_configuring-basic-system-settings#doc-wrapper) and [37](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python_configuring-basic-system-settings) from RH docs.

**Comment by xhernandez** [comment]
> Unfortunately nothing works and I am starting to think that it is by design we have different python versions on el8. See the versions [table](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_introduction-to-python_configuring-basic-system-settings#con_python-versions_assembly_introduction-to-python) from RH docs. Unless we change the default python version, `python3` always indicates `python3.6`. Whereas latest ansible packages that we install are built with latest python version available on el8 i.e, `python3.11`. Therefore as mentioned in the docs:
> 
> > Always specify the version of Python when installing it, invoking it, or otherwise interacting with it.
> 
> Thus we may have to cope with such infrequent python version updates. For better clarity see Chapter [36](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_introduction-to-python_configuring-basic-system-settings#doc-wrapper) and [37](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python_configuring-basic-system-settings) from RH docs.

Thanks a lot for taking a look at this. I just wanted to check if there are better ways, but if not I'm perfectly fine with using explicit versions.

**Review by xhernandez — APPROVED** [review]

**Comment by anoopcs9** [comment]
> > > I think this PR should fix the issue (thanks !), but I'm wondering if there isn't a better way to manage this in general. What if at some point ansible decides to use python 3.12 ? all this will break. Isn't there any other better way to install python dependencies from ansible that is more future-proof ? I've done a quick search but I haven't found anything relevant.
> > 
> > 
> > Before coming up with the change I remember trying to install python library dependencies with the help of **[ansible.builtin.pip](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html)** module. Let me double check to see if it can solve the issue in a more generic way.
> 
> Unfortunately nothing works and I am starting to think that it is by design we have different python versions on el8. See the versions [table](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_introduction-to-python_configuring-basic-system-settings#con_python-versions_assembly_introduction-to-python) from RH docs. Unless we change the default python version, `python3` always indicates `python3.6`. Whereas latest ansible packages that we install are built with latest python version available on el8 i.e, `python3.11`. Therefore as mentioned in the docs:
> 
> > Always specify the version of Python when installing it, invoking it, or otherwise interacting with it.
> 
> Thus we may have to cope with such infrequent python version updates. For better clarity see Chapter [36](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_introduction-to-python_configuring-basic-system-settings#doc-wrapper) and [37](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python_configuring-basic-system-settings) from RH docs.


@phlogistonjohn do you have any other thoughts/suggestions?

**Review by spuiuk — APPROVED** [review]
ACK

**Pull request merged**
